### ISSUE TITLE
What about publishing to npm?

### ISSUE THREAD

**Issue by screeny05** [b3nj4m/chai-webdriver#3]
Oh and try to add a .gitignore to not upload your `node_modules`-folder everytime

**Comment by b3nj4m** [comment]
I was committing `node_modules` for convenience.

Module has been published to npm as `chai-webdriver-promised`. :]

**Comment by screeny05** [comment]
Awesome, thank you very much!
Am 06.10.2014 23:56 schrieb "ben robbins" notifications@github.com:
